[build]
  command = "npm run build"
  publish = "."

[functions]
  directory = "netlify/functions"

[[redirects]]
  from = "/foodarticles/:entryID"
  to = "/.netlify/functions/foodArticle?entryID=:entryID"
  status = 200
  force = true

