[build]
  command = "npm run build"
  publish = "."

[functions]
  directory = "netlify/functions"
  included_files = [
    "src/views/*"
  ]

[[redirects]]
  from = "/foodarticles/:entryID"
  to = "/.netlify/functions/foodArticle?entryID=:entryID"
  status = 200
  force = true
